# Generated by Django 3.1.6 on 2021-02-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('ip_type', models.CharField(max_length=5)),
                ('continent', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('postal', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('how_many', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
