# Generated by Django 3.1.6 on 2021-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='how_many',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ip_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='location',
            name='postal',
        ),
        migrations.AddField(
            model_name='location',
            name='continent_code',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='continent_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country_code',
            field=models.CharField(default=22, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country_name',
            field=models.CharField(default=121, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='region_code',
            field=models.CharField(default=1212323, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='region_name',
            field=models.CharField(default=2323, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(default=3434, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='zip',
            field=models.CharField(default=5554, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default=3434, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
