# Generated by Django 3.1.6 on 2021-02-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApi', '0002_auto_20210217_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ip',
            field=models.CharField(max_length=15),
        ),
    ]
